### PR TITLE
update ffi version and remove ide configuration

### PR DESCRIPTION
**Pull request by wuan**
Updated version of `ffi` dependency to unblock us upstream (This will allow updating to a current version of `version_info_plus` in https://github.com/LeastAuthority/destiny/pull/209).

Bumped version of this library to `0.1.1`.

This PR also removed the IDE internal folders. Please make a copy before pulling these changes.

---

## Code Review Checklist (to be filled out by reviewer)

- [ ] Description accurately reflects what changes are being made.
- [ ] Description explains why the changes are being made (or references an issue containing one).
- [ ] The PR appropriately sized.
- [ ] New code has enough tests. 
- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [ ] Existing documentation is up-to-date if impacted.

### CODE REVIEW

**Comment by meejah** [comment]
I think we would really benefit from following a workflow where we have "tickets" that then have "a PR which fixes a ticket" because we very often don't have the "why" answered in a lot of wormhole tickets.

This one comes closer than a lot, but "Updated version of ffi dependency to unblock us upstream" doesn't tell a future reader or reviewer what the problem actually is/was, for example.

**Comment by wuan** [comment]
In this case we have a very clear technical why in https://github.com/LeastAuthority/destiny/pull/209. I do not see why we should create a ticket:

> Update dependency version to unblock other project.

and then open a PR with

> Update dependency version to unblock other project. Fixing `#<ticket>`.

This is just a technical task no story where we have to be clear on common requirements.

**Comment by meejah** [comment]
It's certainly way _more_ clear after your description-edit, and I don't mean to pick on _this_ ticket in particular (like I said, it's better than lots because it actually has _some_ description) it's more of a general ask.

**Review by donpui — APPROVED** [review]
With iOS I have also updated ffi to newest version, from my side it should be ok.

**Pull request merged**
